# Generated by Django 5.0.3 on 2024-03-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VotingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('constituency', models.CharField(max_length=20)),
            ],
        ),
    ]
